import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html lang='zh'>
        <Head>
          {/* <title>Create Next App</title> */}
          {/* <meta name='description2' content='Generated by create next app' /> */}

          <meta name='description' content='叶肇才个人简历' />
          <meta name='author' content='yxc' />
          <meta
            name='keywords'
            content='yxc,resume,Html,JavaScript,Vue,React'
          />
          {/* <meta name='viewport' content='width=device-width,initial-scale=1' /> */}
          <link rel='icon' href='/favicon.ico' />
          {/* <link
            rel='stylesheet'
            href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
          /> */}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
